import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Container } from './styles';

const Home: NextPage = () => {
    return (
        <Container>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <h1>Hello World</h1>
        </Container>
    );
};

export default Home;
